select = [
  "ALL",
]

ignore = [
  "I",      # isort
  "TD",     # flake8-todos
  "FIX",    # flake8-fixme
  "ANN002", # missing-type-args
  "ANN003", # missing-type-kwargs
  "ANN101", # missing-type-self
  "D100",   # undocumented-public-module
  "E501",   # Line too long
  "N818",   # Exceptions without -Error suffix
  "S101",   # flake8-bandit: assert
  "TRY003", # raise-vanilla-args
]

target-version = "py311" # min=py37


[pydocstyle]
convention = "google"
