# Same as Black.
line-length = 88
indent-width = 4

target-version = "py311" # min=py37


[lint]
select = [
  "ALL",
]

ignore = [
  "ANN002", # missing-type-args
  "ANN003", # missing-type-kwargs
  "ANN101", # missing-type-self
  "D100",   # undocumented-public-module
  "E501",   # Line too long
  "EM101",  # raw-string-in-exception, we like raw
  "EM102",  # f-string-in-exception
  "FBT001", # boolean-type-hint-positional-argument
  "FBT002", # boolean-default-value-positional-argument
  "FIX",    # flake8-fixme
  "I",      # isort
  "N818",   # Exceptions without -Error suffix
  "S101",   # flake8-bandit: assert
  "TD",     # flake8-todos
  "TRY003", # raise-vanilla-args
  "UP038",  # non-pep604-isinstance, we want more performance
]

[lint.per-file-ignores]
"**/tests/*" = ["D", "ANN201", "PLR0913"]

[pydocstyle]
convention = "google"
